
#if !defined(ETH_30_VTT_LL_CFG_H)
# define     ETH_30_VTT_LL_CFG_H

# define ETH_30_VTT_IMPLEMENTATION_INIT                     (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_INIT_MEMORY              (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_CONTROLLER_INIT          (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_SET_CONTROLLER_MODE      (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_GET_CONTROLLER_MODE      (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_GET_PHYS_ADDR            (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_SET_PHYS_ADDR            (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_UPDATE_PHYS_ADDR_FILTER  (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_WRITE_MII                (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_READ_MII                 (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_GET_COUNTER_STATE        (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_PROVIDE_TX_BUFFER        (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_TRANSMIT                 (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_VTRANSMIT                (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_RECEIVE                  (STD_OFF)
# define ETH_30_VTT_IMPLEMENTATION_TX_CONFIRMATION          (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_MAINFUNCTION             (STD_ON)
# define ETH_30_VTT_IMPLEMENTATION_GET_VERSION_INFO         (STD_ON)

#endif /* ETH_30_VTT_LL_CFG_H */

