/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: D:\TEMP\Cfg_Gen-1466772298513-0\OsProxyFiles-1466772714071-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Fri Jun 24 14:51:58 2016 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF A:\_E1_SoftwareComponents\trunk\Appl\GenDataVtt\msg.c */

